fldmon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from main.views import (
	RegisterView, IndexView, LoginView,
	ReportFlood, AddFloodProneAreaView, InspectFlood,
	)
from django.views.generic import TemplateView

app_name='fldast'
urlpatterns = [
	path('', IndexView.as_view(), name='index'),
	path('register', RegisterView.as_view(), name='register'),
	path('login', LoginView.as_view(), name='login'),
	path('report-flood', ReportFlood.as_view(), name='report-flood'),
	path('flood-state/', InspectFlood.as_view(), name='flood-state'),
	path('add-flood-prone-area', AddFloodProneAreaView.as_view(), name='add-flood-prone-area'),
	path('success/', TemplateView.as_view(template_name='main/success.html'), name='success')
]

main/models.py
from django.contrib.gis.db import models
from decimal import Decimal

# Create your models here.
class WorldBorder(models.Model):
	"""World borders"""
	fips = models.CharField(max_length=2)
	iso2 = models.CharField(max_length=2)
	iso3 = models.CharField(max_length=3)
	un = models.IntegerField()
	name = models.CharField(max_length=50)
	area = models.IntegerField()
	pop2005 = models.BigIntegerField()
	region = models.IntegerField()
	subregion = models.IntegerField()
	lon = models.FloatField()
	lat = models.FloatField()
	geom = models.MultiPolygonField(srid=4326)

class FloodIncidents(models.Model):
	name = models.CharField(max_length=125)
	description = models.CharField(max_length=600, blank=True)
	geom = models.GeometryField(srid=4326)
	date = models.DateTimeField(auto_now_add=True, null=True)
	level = models.DecimalField(max_digits=4, decimal_places=4, default=Decimal('0.0000'))
	confirmed = models.BooleanField(default=False)

	def save(self):
		super(FloodIncidents, self).save()
		
	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Flood Areas"

class FloodProneArea(models.Model):
	name = models.CharField(max_length=55)
	description = models.CharField(max_length=1000)
	avg_rainfall = models.DecimalField(decimal_places=4, max_digits=10, help_text="Average rainfall per month", blank=True, null=True)
	msl = models.DecimalField(decimal_places=4, max_digits=10, help_text="Mean Sea Level", blank=True, null=True)
	peak = models.PointField(srid=4326, help_text="The highest point of this area", blank=True, null=True)
	#folder = models.URLField(help_text="File folder for this area", blank=True, null=True)
	geom = models.PolygonField(srid=4326)


	def __str__(self):
		return self.name

class River(models.Model):
    cat = models.BigIntegerField()
    area = models.FloatField()
    up_cells = models.BigIntegerField()
    discharge = models.FloatField()
    width = models.FloatField()
    width5 = models.FloatField()
    width95 = models.FloatField()
    depth = models.FloatField()
    depth5 = models.FloatField()
    depth95 = models.FloatField()
    arcid = models.BigIntegerField()
    geom = models.MultiLineStringField(srid=4326)
    

main/forms.py
from django import forms
from leaflet.forms.widgets import LeafletWidget
from main.models import FloodIncidents, FloodProneArea
class ReportFloodForm(forms.ModelForm):
    
    class Meta:
        model = FloodIncidents
        fields = ['name', 'description', 'geom']
        widgets = {'geom': LeafletWidget()}

class AddFloodProneAreaForm(forms.ModelForm):
    #geomFile = forms.FileField()

    class Meta:
        model = FloodProneArea
        fields = '__all__'
        widgets = {
            'description':forms.Textarea(attrs={'width':'100%', 'min-height':'250px'}),
            'geom': LeafletWidget()
        }
        

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from main.models import WorldBorder, River
from main.models import FloodIncidents as fds
from django.core.serializers import serialize
from main.forms import ReportFloodForm, AddFloodProneAreaForm, FloodProneArea as fdp
from django.contrib.gis import geos
from rest_framework.response import Response
from rest_framework.views import APIView

#shapely imports
from shapely.geometry import Point, Polygon, shape, mapping
from functools import partial
import pyproj
from shapely.ops import transform
from django.contrib.gis import geos

#For eolearn
from eolearn.io import S2L1CWCSInput, DEMWCSInput
from eolearn.core import EOTask, EOPatch, LinearWorkflow, Dependency, FeatureType, LoadFromDisk, SaveToDisk
from sentinelhub import BBox, CRS
import numpy as np
from osgeo import gdal
import matplotlib.pyplot as plt

#concurencies
import asyncio

#datetime imprts
from datetime import datetime, timedelta, date
from django.utils import timezone
# Create your views here.

#IBM weather api
import weatherapi.app as weatherapi
class IndexView(TemplateView):
	def __init__(self):
		self.world_borders = None
		self.active_country = None
		self.active_country_geojson = None
		self.active_country_name = 'Kenya'
		self.reported_incidents = []
		self.center = (0,0)
		

	template_name = "main/index.html"
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		today = timezone.now()
		three_days_before = today+timedelta(days=-3)
		date_str = 'today'
		self.world_borders = WorldBorder.objects.all()
		self.active_country = self.world_borders.filter(name=self.active_country_name)
		self.active_country_geojson = serialize('geojson', self.active_country)
		self.reported_incidents = fds.objects.filter(geom__within=self.active_country[0].geom)
		self.recent_incidents = fds.objects.filter(date__range=[str(three_days_before), str(today)])
		self.prone_ares = fdp.objects.all()
		geom = geos.GEOSGeometry(self.active_country[0].geom)
		context['center'] = geom.centroid.coords
		context['latitude']=geom.centroid.coords[1]
		context['longitude']=geom.centroid.coords[0]
		context['countries']=self.world_borders
		context['selected_country'] = self.active_country[0]
		context['selected_country_geojson'] = self.active_country_geojson
		context['incidents'] = self.reported_incidents
		context['recent_incidents'] = self.recent_incidents
		context['prone_area'] = self.prone_ares
		return context

class RegisterView(generic.CreateView):
	form_class = UserCreationForm
	template_name = 'main/register.html'
	success_url = 'login'
	
class LoginView(TemplateView):
	template_name = "main/login.html"

	def get_context_data(self, **kwargs):
		context = super(LoginView, self).get_context_data(**kwargs)
		print(self.request.user.id)
		#User.objects.filter(pk=self.request.user.id)
		context['user'] = User

class ReportFlood(generic.CreateView):
	template_name = "main/report-flood.html"
	form_class = ReportFloodForm
	success_url = 'success/'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['form'] = ReportFloodForm
		return context

class AddFloodProneAreaView(generic.CreateView):
	template_name = "main/add-flood-prone-area.html"
	form_class = AddFloodProneAreaForm
	success_url = 'success/'

class InspectFlood(APIView):
	def __init__(self):
		self.area = ""
		self.nearby_rivers = []
		self.longitude = 0.0
		self.latitude = 0.0
		self.geometry = Point(0,0)
		self.proj_wgs84 = pyproj.Proj(init='epsg:4326')
		self.radius = 3
		self.response = {}

	def geodesic_point_buffer(self, lat, lng, km):
		aeqd_proj = '+proj=aeqd + lat_0={lat} +lon_0={lng} +x_0=0 +y_0=0'
		project = partial(pyproj.transform, pyproj.Proj(aeqd_proj.format(lat=lat, lng=lng)), self.proj_wgs84)
		buff = Point(0,0).buffer(km*1000)
		return transform(project, buff).exterior.coords[:]

	def get(self, request, **kwargs):
		params = request.GET
		if params:
			print()
			self.latitude = round(float(params.get('lat')), 4)
			self.longitude = round(float(params.get('lng')), 4)
			self.radius = int(params.get('radius'))
			self.geometry = self.geodesic_point_buffer(self.latitude, self.longitude, self.radius)
			geosGeom = geos.Polygon(self.geometry)
			self.near_rivers = River.objects.filter(geom__intersects=geosGeom)
			self.nearby_rivers = serialize('geojson',self.near_rivers)
			self.response['lat'] = self.latitude
			self.response['lng'] = self.longitude
			self.response['nearby_rivers'] = self.nearby_rivers
			self.response['geometry'] = mapping(Polygon(self.geometry))
			self.response['flood_prone'] = self.is_flood_prone_area(geosGeom)
			#eopatch = self.get_elevation(Polygon(self.geometry).bounds)
			#eopatch_sq = eopatch.data_timeless['MAPZEN_DEM'].squeeze()
			self.response['mean_slope'] = np.random.rand()#self.calclute_slope(eopatch_sq).mean()
			self.response['msl'] = np.random.uniform(low=600, high=4000, size=None)#self.calculate_mean_sea_level(eopatch_sq)
			self.response['rain_prediction'] = self.get_rain_prediction(self.latitude, self.longitude)
			self.response['remarks']=self.determine_flood_safe()
			"""plt.figure(figsize=(10,10))
			plt.imshow(eopatch.data_timeless['MAPZEN_DEM'].squeeze())
			plt.show()"""
			
		else:
			print("No query params")

		return Response(self.response)

	def get_elevation(self, bounds):
		INSTANCE_ID = '4aaea2ec-3a2c-4e1c-8a51-851e220d0273'
		roi = BBox(bbox=bounds, crs=CRS.WGS84)
		layer = 'MAPZEN_DEM'
		time_interval = ('2019-01-01', '2019-06-01')
		add_dem = DEMWCSInput(layer=layer, instance_id=INSTANCE_ID)
		input_task = S2L1CWCSInput(layer=layer, resx='30m', resy='30m', instance_id=INSTANCE_ID)
		workflow = LinearWorkflow(input_task, add_dem)
		result = workflow.execute({input_task:{'bbox':roi, 'time_interval':time_interval}})
		eopatch = list(result.values())[0]
		
		return eopatch

	def calclute_slope(self, dem_array):
		slope = np.gradient(dem_array[0], dem_array[1])
		return slope[~np.isnan(slope)]


	def calculate_mean_sea_level(self, dem_array):
		dem_no_nan = dem_array[~np.isnan(dem_array)]
		return dem_no_nan.mean()


	def is_flood_prone_area(self, area):
		return True if fdp.objects.filter(geom__intersects=area) else False

	def get_rain_prediction(self, lat, lon):
		return weatherapi.callWhenWillItRain(str(lat), str(lon))

	def determine_flood_safe(self):
		rivers_width_greater_than_20 = [river for river in self.near_rivers if river.width > 20]
		dangerous_rivers = [river for river in rivers_width_greater_than_20 if river.discharge < 1]
		dangerous_slope = self.response['msl'] < 1
		alert = ''
		if(self.response['rain_prediction']['precip_time_iso'] and self.response['flood_prone']):
			alert = 'Flooding may occur in the next 6 hours'
		
		remarks = {
			'wide_rivers':len(rivers_width_greater_than_20),
			'dangerous_rivers':len(dangerous_rivers),
			'dangerous_slope':dangerous_slope,
			'alert':alert
		}
		return remarks

main/templates/main/add-flood-prone-area.html
{% extends 'main/base.html' %}
{% load leaflet_tags %}
{% load widget_tweaks %}
{% load static %}
{% block head_content %}
	
	{% leaflet_js %}
    {% leaflet_css %}
    {% leaflet_css plugins="forms" %}
    {% leaflet_js plugins="forms" %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.deep_purple-pink.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <style>
        .mdl-card{
            width: 100%;
        }
    </style>
{% endblock head_content %}

{% block content %}
<div class="container-fluid">
		<div class="justify-content-center">
			<!-- Simple Textfield -->
			<form action="{% url 'fldast:add-flood-prone-area' %}" method="POST" class="mt-5">
                {% csrf_token %}
				<div class="demo-card-wide mdl-card mdl-shadow--2dp">
					<div class="mdl-card__title">
						<h2 class="mdl-card__title-text">New Flood Prone Area</h2>
					</div>
					<div class="mdl-card__supporting-text">
						Add Flood prone area, make people to be alert
                    </div>
                    <div class="row mr-3 ml-3">
                        <div class="col">
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                                    {% render_field form.name class="mdl-textfield__input" %}
                                    <label class="mdl-textfield__label" for="{{form.name.name}}" style="margin-bottom: 0px">{{ form.name.name }}</label>
                                    {% if form.name.help_text %}
                                        <small class="form-text text-muted">{{ form.name.help_text }}</small>
                                    {% endif %}
                                    {% for error in form.name.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div><br>
        
                                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                                    {% render_field form.description class="mdl-textfield__input" %}
                                    <label class="mdl-textfield__label" for="{{form.description.name}}" style="margin-bottom: 0px">{{ form.description.name }}</label>
                                    {% if form.description.help_text %}
                                        <small class="form-text text-muted">{{ form.description.help_text }}</small>
                                    {% endif %}
                                    {% for error in form.description.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>    
                            </div>

                        <div class="col">
                                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                                        {% render_field form.msl class="mdl-textfield__input" %}
                                        <label class="mdl-textfield__label" for="{{form.msl.name}}" style="margin-bottom: 0px">{{ form.msl.name }}</label>
                                        {% if form.name.help_text %}
                                            <small class="form-text text-muted">{{ form.msl.help_text }}</small>
                                        {% endif %}
                                        {% for error in form.msl.errors %}
                                            <span class="help-block">{{ error }}</span>
                                        {% endfor %}
                                    </div><br>


                                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                                            {% render_field form.avg_rainfall class="mdl-textfield__input" %}
                                            <label class="mdl-textfield__label" for="{{form.avg_rainfall.name}}" style="margin-bottom: 0px">{{ form.avg_rainfall.name }}</label>
                                            {% if form.name.help_text %}
                                                <small class="form-text text-muted">{{ form.avg_rainfall.help_text }}</small>
                                            {% endif %}
                                            {% for error in form.avg_rainfall.errors %}
                                                <span class="help-block">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                        </div>

                        <div class="col">
                            {% render_field form.geom %}
                            
                        </div>
                        <div class="form-group  mt-2" style="position: relative; bottom: 0;">
                                <button class="btn btn-outline-info" type="submit">Add</button>
                            </div>
                    </div>
                
                </div>

					
			</form>  
		</div>
		
	</div>
{% endblock content %}

main/templates/main/base.html
<!DOCTYPE html>
<html>
	<head>
		{% load bootstrap4 %}
		{% bootstrap_css %}
		{% bootstrap_javascript jquery='full' %}
		{% bootstrap_messages %}
		
		{% block head_content %}
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.deep_purple-pink.min.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
		<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
		{% endblock head_content %}

		{% if title %}
			<title>fldmn - {{title}}</title>
		{% else %}
			<title>fldmn</title>
		{% endif %}
	</head>

	<body>
		{% block content %}{% endblock %}
	</body>
</html>

main/templates/main/login.html
Login to continue
{{ user }}

main/templates/main/register.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    {% endfor %}
	</ul>
	{% endif %}
	
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}	
		<button type="submit">Submit</button>
	</form>
	
</body>
</html>

main/templates/main/report-flood-success.html
{% extends 'main/base.html' %}

{% block content %}
    <h1>Thank you for reporting!</h1>
{% endblock content %}

main/templates/main/report-flood.html
{% extends 'main/base.html' %}
{% load leaflet_tags %}

{% block head_content %}
    {% leaflet_css plugins="forms" %}
    {% leaflet_js plugins="forms" %}
{% endblock head_content %}

{% block content %}
    <div class="container">
        <h1>Thank you for reaching out, Kindly fill this form </h1>
        {{ object }}
        <form method="POST" class="form">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Report">
        </form>
    </div>
    
{% endblock content %}

main/templates/main/success.html
{% extends 'main/base.html' %}
{% load static %}
{% block head_content %}

{% endblock head_content %}

{% block content %}

<div class="container h-100 justify-content-center align-items-center">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-12"><h2 style="color:green">Success!</h2><br></div>
        <div class="col-12"><a href="{% url 'fldast:index' %}"><button type="button" class="btn btn-success">Go to Home page</button></a></div>
    </div>
    
</div>
{% endblock content %}